### ISSUE TITLE
small enhancements for message count

### ISSUE THREAD

**Issue by stmolivier** [claroline/ForumBundle#70]
i have posted a message on [claroline forum](http://www.claroline.net/forum/11/category) , then someone responded and i responded back and i saw that : 
- on forum level (list of forum): it was displayed "3 messages", where in fact it should be 1 message (the responses should not be included)
- on a message level : it is displayed "3 responses" where in fact it should be 2 (the initial message should not be considered as a response)

thank you

**Comment by ngodfraind** [comment]
This will be fixed for the next release.
